sudo: required
branches:
    except:
        - /^phabricator/base/.*$/
deploy:
    provider: s3
    bucket: $DEPLOYMENT_BUCKET
    skip_cleanup: true
    upload_dir: travis-builds
    local_dir: deploy
    on:
        all_branches: true
before_deploy:
    - |
      ./scripts/live-ci-tools/build-travis-distribution.py \
        dist \
        --output-directory deploy \
        --suffix $TARGET \
        --exclude needy.status
addons:
    artifacts:
        bucket: $DEPLOYMENT_BUCKET/travis-artifacts
        paths:
          - $(find analysis | tr "\n" ":")

matrix:
    include:

        # Android
        - os: linux
          language: android
          compiler: clang
          env:
              - NDK_VERSION=r10e
              - API_LEVEL=17
              - TARGET=android
          android:
              components:
                  - android-22
                  - build-tools-23.0.1
          install: ./scripts/ci/install-android-dependencies
          script:  ./scripts/ci/build-android

        # Linux
        - os: linux
          language: cpp
          dist: trusty
          compiler: clang
          env:
              - TARGET=linux
          install: ./scripts/ci/install-linux-dependencies
          script:  ./scripts/ci/build-linux
          after_success: bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.8 gcov"

        ######### Xcode #########

        # MacOS
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=macos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-macos
          after_success: bash <(curl -s https://codecov.io/bash)

        # iPhone
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=iphoneos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-iphoneos

        # AppleTV
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=appletvos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-appletvos
