sudo: required
cache:
    directories:
        - needs
        - toolchains
matrix:
    include:
        - os: linux
          language: android
          compiler: clang
          env:
              - NDK_VERSION=r10e API_LEVEL=17
          android:
              components:
                  - android-22
                  - build-tools-23.0.1
          install:
              - ./scripts/ci/install-android-dependencies
          script:
              - ./scripts/ci/build-android
        - os: linux
          language: cpp
          dist: trusty
          compiler: clang
          install:
              - ./scripts/ci/install-linux-dependencies
          script:
              - ./scripts/ci/build-linux
          after-success:
              - bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.8 gcov"
        - os: osx
          language: cpp
          osx_image: xcode8
          install:
              - ./scripts/ci/install-macos-dependencies
          script:
              - ./scripts/ci/build-macos
        - os: osx
          language: cpp
          osx_image: xcode7.3
          install:
              - ./scripts/ci/install-macos-dependencies
          script:
              - ./scripts/ci/build-macos
