sudo: required
branches:
    except: /^phabricator/base/.*$/
deploy:
    provider: s3
    bucket: $DEPLOYMENT_BUCKET
    skip_cleanup: true
    upload_dir: travis-builds
    local_dir: deploy
    on:
        all_branches: true
before_deploy:
    - |
      ./scripts/live-ci-tools/build-travis-distribution.py \
        dist \
        --output-directory deploy \
        --suffix $TARGET \
        --exclude needy.status
addons:
    artifacts:
        bucket: $DEPLOYMENT_BUCKET/travis-artifacts
        paths: $(find analysis | tr "\n" ":")

matrix:
    include:

        # Android
        - os: linux
          services: docker
          language: generic
          env: TARGET=android
          install: docker-compose pull android-env
          script:
              - |
                docker-compose run \
                  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                  -e CACHE_BUCKET=$CACHE_BUCKET \
                  -e TRAVIS=true -e CI=true \
                  --rm android-env \
                bash -c \
                  "./scripts/ci/install-android-dependencies && \
                  ./scripts/ci/build-android"

        # Linux
        - os: linux
          language: generic
          env: TARGET=linux
          dist: trusty
          install: docker-compose pull linux-env
          script:
              - |
                docker-compose run \
                  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                  -e CACHE_BUCKET=$CACHE_BUCKET \
                  -e TRAVIS=true -e CI=true \
                  --rm linux-env \
                bash -c \
                  "./scripts/ci/install-linux-dependencies && \
                  ./scripts/ci/build-linux"
          after_success:
              - |
                docker-compose run \
                  --rm linux-env \
                bash -c 'bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.8 gcov"'

        ######### Xcode #########

        # MacOS
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=macos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-macos
          after_success: bash <(curl -s https://codecov.io/bash)

        # iPhone
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=iphoneos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-iphoneos

        # AppleTV
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     TARGET=appletvos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-appletvos

        ############ Analysis ############

        # Linux
        - os: linux
          language: generic
          env:
              - TARGET=linux
              - ANALYSIS=1
          dist: trusty
          install: docker-compose pull linux-env
          script:
              - |
                docker-compose run \
                  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                  -e CACHE_BUCKET=$CACHE_BUCKET \
                  -e ANALYSIS=$ANALYSIS \
                  -e TRAVIS=true -e CI=true \
                  --rm linux-env \
                bash -c \
                  "./scripts/ci/install-linux-dependencies && \
                  ./scripts/ci/build-linux"

        # MacOS
        - os: osx
          language: cpp
          osx_image: xcode8
          env:
            - TARGET=macos
            - ANALYSIS=1
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-macos
