sudo: required
branches:
    except: /^phabricator/base/.*$/
deploy:
    provider: s3
    bucket: $DEPLOYMENT_BUCKET
    skip_cleanup: true
    upload_dir: travis-builds
    local_dir: deploy
    on:
        all_branches: true
before_deploy:
    - |
      ./scripts/live-ci-tools/build-travis-distribution.py \
        dist \
        --output-directory deploy \
        --suffix $TARGET \
        --exclude needy.status
addons:
    artifacts:
        bucket: $DEPLOYMENT_BUCKET/travis-artifacts
        paths: $(find analysis | tr "\n" ":")

matrix:
    include:

        # Linux
        - os: linux
          language: generic
          env: TARGET=linux
          dist: trusty
          install: docker-compose pull linux-env
          script:
              - |
                docker-compose run \
                  -e AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY \
                  -e CACHE_BUCKET \
                  -e TRAVIS -e CI \
                  --rm linux-env \
                bash -c \
                  "./scripts/ci/install-linux-dependencies && \
                  ./scripts/ci/build-linux"
          after_success:
              - |
                docker-compose run \
                  $(./scripts/live-ci-tools/docker-env.py --with-codecov) \
                  --rm linux-env \
                bash -c 'bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.9 gcov"'

        # Analysis
        - os: linux
          language: generic
          env:
              - TARGET=linux
              - ANALYSIS=1
          dist: trusty
          install: docker-compose pull linux-env
          script:
              - |
                docker-compose run \
                  -e AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY \
                  -e CACHE_BUCKET \
                  -e ANALYSIS \
                  -e TRAVIS -e CI \
                  --rm linux-env \
                bash -c \
                  "./scripts/ci/install-linux-dependencies && \
                  ./scripts/ci/build-linux"
