language: cpp
dist: trusty
sudo: required
compiler: clang
install:
    - pip install --user jinja2 pyyaml
    - sudo apt-get update
    - sudo apt-get install -y clang-3.8 libc++-dev libc++abi-dev xutils-dev
script:
    - export CXX=clang++-3.8
    - export CXXFLAGS=-stdlib=libc++
    - "echo 'using clang : : $CXX : <cxxflags>$CXXFLAGS <linkflags>$CXXFLAGS ;' > project-config.jam"
    - ./build-deps --bootstrap-b2 --configure && ./b2 tests//run -j2 cxxflags="-coverage" linkflags=`find /usr/lib*/llvm-3.8/lib/ -name "libclang_rt.profile*.a"`
after_success:
    - bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.8 gcov"
