version: '2'
services:
    base:
        image: dummy
        working_dir: /mnt/scraps
        volumes:
            - .:/mnt/scraps
    linux-env:
        extends:
            service: base
        image: bittorrent/live-build-environments:linux-73a78cb
    android-env:
        extends:
            service: base
        image: bittorrent/live-build-environments:android-n17-s22-arm-486fb54
        environment:
            - SCRAPS_CROSS_TARGET=android
