version: '2'
services:
    android-env:
        image: bittorrent/live-build-environments:android-17-arm-0992bb7
        working_dir: /mnt/scraps
        volumes:
            - .:/mnt/scraps
    linux-env:
        image: bittorrent/live-build-environments:linux-73a78cb
        working_dir: /mnt/scraps
        volumes:
            - .:/mnt/scraps
